import type { Metadata } from "next";
import "../globals.css";
import NavBar from "../_components/navBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head></head>
      <body>
        <NavBar />

        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  );
}
