import type { Metadata } from "next";
import "../globals.css";
import NavBar from "../_components/navBar";
import Footer from "../_components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head><link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      </head>
      <body>
        <NavBar />
        
        {children}

        <Footer />
      </body>
    </html>
  );
}
